# Nixpacks Configuration
# This file customizes the build process for Coolify deployments

[phases.setup]
nixPkgs = ["nodejs_22", "bun"]

[phases.install]
cmds = ["bun install"]

[phases.build]
# Build command será definido no Coolify para cada ambiente:
# Production: bun run build:prod
# Development: bun run build:dev
# Remove cache problemático do tsconfig.tsbuildinfo
cacheDirectories = ["node_modules/.cache"]

[start]
# Start command será definido no Coolify
# Both envs: bun run start
